version: "3.8"
services:

  nexus:
    image: sonatype/nexus:oss
    ports:
      - "8081:8081"

  nuxeo-builder:
    build:
      context: ./nuxeo-builder
    depends_on:
      - nexus
    volumes:
      - ./nuxeo-builder_build-volume:/media/build-volume
